lifeomic/chroma-react

- src/styles/overrides/ChromaOverrides.ts
@ynotdraw Not sure if I need to do anything else when adding overrides?
> Export ButtonFloat and IconButtonFloat overrides

- .github/workflows/release.yml
- I noticed the build output was not what's published to npm, instead it's the raw source.  This PR _should_ fix that.
> FIX: Update publish to use dist

- README.md
BEST OPEN-SOURCE CONTRIBUTION EVER!
> fix: Yarn install instructions, name of package being installed.

- package.json
**Changes**
- Bump version
- [Changes](https://github.com/lifeomic/chroma-react/pull/19): Added new align values for `<Box`
> Chroma Version - v0.1.4

- package.json
**Changes**
- Version for updated [changes](https://github.com/lifeomic/chroma-react/pull/21) to ComboBox
> CHROMA - v0.1.5

- src/components/TableModule/TableHeaderCell.test.tsx
- src/components/TableModule/TableModuleCell.test.tsx
- Related to https://github.com/lifeomic/chroma-react/pull/31, I decided to rewrite some of the tests to have clearer assertions
> TESTS: Improve Table Module test cases

- src/components/Radio/RadioGroup.test.tsx
- src/components/Radio/RadioGroup.tsx
Radio Group value was not updating when the value prop changes
> Fix Issue where RadioGroup Did Not Update Value When Prop Changed

- src/components/PrimaryNavigation/PrimaryNavigation.tsx
**Changes**
- Updated footer text color for accessibility 
**BEFORE**
**AFTER**
> PHC-463 Primary Nav Text

- src/components/TextField/TextField.test.tsx
- src/components/TextField/TextField.tsx
**Changes**
- Conditionally rendered label and added `aria-label` to input field
> PHC-463 TextField label

- src/styles/createTheme.ts
Using this to create custom theme properties
> export ThemeOptions

- src/components/ButtonUnstyled/ButtonUnstyled.tsx
**Changes**
- Added `color: "inherit"` to root
**BEFORE**
**AFTER**
> ButtonUnstyled - add color inherit

- src/colors/blue.ts
- src/components/Button/Button.tsx
- src/styles/__snapshots__/createTheme.test.ts.snap
**Changes**
- Updated primary color from primary `600` -> `800` 
- Updated a few `<Button` hover colors from primary `800` -> `900`
**BEFORE**
(**Disabled**)
**AFTER**
(**Disabled**)
> A11y Button 

- src/components/IconTile/IconTileContent.tsx
**Changes**
- Updated caption color
**BEFORE**
**AFTER**
> A11y IconTile

- src/components/SmallTile/SmallTileFooter.tsx
**Changes**
- Updated footer text color
**BEFORE**
**AFTER**
> A11y SmallTile

- src/components/_private/forms/FormHelpMessage.tsx
> a11y Inverse help messages

- stories/components/ComboBox/ComboBox.stories.tsx
- stories/components/Divider/Divider.stories.tsx
- stories/components/FormBox/FormBox.stories.tsx
- stories/components/Link/Link.stories.tsx
- stories/components/SearchField/SearchField.stories.tsx
- stories/components/Select/Select.stories.tsx
- stories/components/TableModule/TableModule.stories.tsx
- stories/components/TextArea/TextArea.stories.tsx
- stories/components/TextField/TextField.stories.tsx
- stories/components/Toggle/Toggle.stories.tsx
**Changes**
- Updated background color to main
- Fixed label error for TableModule story
**BEFORE**
**AFTER**
**BEFORE**
**AFTER**
**BEFORE**
**AFTER**
> A11y - Stories updates

- src/assets/PageLayoutDefaultHero.svg
- src/components/IconButton/IconButton.tsx
- src/components/IconButtonLink/IconButtonLink.tsx
- src/components/Stepper/Step.tsx
**Changes**
- Updated pill color in Step component
- Updated fill color on PageLayout SVG
- Updated IconButton focus color to match hover color
**BEFORE**
**AFTER**
**BEFORE**
**AFTER**
**BEFORE**
**AFTER**
> A11y - Last pass color contrast

- src/components/TextField/TextField.tsx
> a11y TextField contrast

- src/components/Select/GroupHeading.tsx
- src/components/Select/Select.tsx
- stories/components/ComboBox/ComboBox.stories.tsx
- stories/components/Select/Select.stories.tsx
&nbsp; | BEFORE | AFTER
-- | -- | --
Select | <img width="1195" alt="Screen Shot 2021-03-17 at 5 17 50 PM" src="https://user-images.githubusercontent.com/485903/111540329-6613d100-8745-11eb-867b-13a1dd05fdb4.png"> | <img width="1195" alt="Screen Shot 2021-03-17 at 5 18 28 PM" src="https://user-images.githubusercontent.com/485903/111540331-66ac6780-8745-11eb-894a-b69bec33df97.png">
ComboBox | <img width="1069" alt="Screen Shot 2021-03-17 at 5 19 40 PM" src="https://user-images.githubusercontent.com/485903/111540532-a2dfc800-8745-11eb-876d-f3db119a7445.png"> | <img width="1069" alt="Screen Shot 2021-03-17 at 5 20 16 PM" src="https://user-images.githubusercontent.com/485903/111540537-a410f500-8745-11eb-8522-18520eb14a23.png">
> a11y Select and ComboBox contrast

- src/components/SearchField/SearchField.tsx
- stories/components/SearchField/SearchField.stories.tsx
> a11y SearchField contrast

- stories/components/FormBox/FormBox.stories.tsx
> Add Radio Group Minimal to FormBox demo

- src/components/TextArea/TextArea.tsx
- stories/components/TextArea/TextArea.stories.tsx
Add aria labels to TextArea demo so a11y checks pass
> Get TextArea story to pass a11y checks

- src/components/Select/ComboBox.tsx
- src/components/Select/Select.tsx
> PHC-1172: updating styles for Select and Combobox (IE 11)

- package.json
Just bumping the version again for another IE fix
> Version bump (v0.4.6)

- src/components/Radio/Radio.tsx
- src/components/Select/RoverOption.tsx
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
- src/components/Select/SelectOption.tsx
- stories/components/Select/Select.stories.tsx
Co-authored-by: ynotdraw <tony.ward@lifeomic.com>
**Changes**
- Add `disabled` property to `SelectOption`
https://user-images.githubusercontent.com/32574227/119710461-64911400-be2c-11eb-825f-a4887702c046.mov
> Select option disabled

- stories/components/ComboBox/default.md
**Changes**
- Fixed broken component source code link for `ComboBox`
> ComboBox broken story link

- src/components/Select/ComboBox.test.tsx
- src/components/Select/ComboBox.tsx
- stories/components/ComboBox/ComboBox.stories.tsx
**Changes**
- Fixed disabled options from being selectable
**BEFORE**
https://user-images.githubusercontent.com/32574227/121196575-9b105b00-c83e-11eb-9d33-4d5e9ac4dace.mov
**AFTER**
https://user-images.githubusercontent.com/32574227/121196561-98156a80-c83e-11eb-9b03-83a3018e830e.mov
> Combo box disabled options

- src/components/ColorPicker/ColorPicker.test.tsx
- src/components/ColorPicker/ColorPicker.tsx
- src/components/ColorPicker/index.ts
- src/components/Modal/Modal.tsx
- src/styles/overrides/ChromaOverrides.ts
- stories/components/ColorPicker/ColorPicker.stories.tsx
- stories/components/ColorPicker/default.md
**Changes**
- Added color picker
https://user-images.githubusercontent.com/32574227/122842556-a007ec80-d2cb-11eb-8b85-441765839f12.mov
> Color picker

- src/components/NumberFormat/UnitNumberFormatField.tsx
- src/components/NumberFormat/index.ts
- yarn.lock
I realized the prop types for these components were not being exported. They are now.
> Export prop types from NumberFormat

- stories/components/Icons/adaptiveIcons.md
- stories/components/Icons/filledIcons.md
- stories/components/Icons/linedCustomIcons.md
- stories/components/Icons/linedIcons.md
- stories/components/Icons/overview.md
- Add deprecation notice to icon docs
> DOCS: Add deprecation notice to icon docs

- stories/components/Stepper/Stepper.stories.tsx
- Don't import from feather
- https://github.com/lifeomic/chroma-react/runs/3125997468?check_suite_focus=true
> docs: Fix broken icon import

- package.json
- yarn.lock
- Use latest 1.0.0 version of Chromicons package
> fix: Use latest ^1.0.0 of chromicons

- package.json
- src/components/Radio/Radio.test.tsx
- src/components/Radio/Radio.tsx
- yarn.lock
In reference to thread in slack channel #frontend-dev
> fix: Larger radio clickbox

- package.json
- yarn.lock
See [this internal Slack thread](https://lifeomic.slack.com/archives/CHMFL4PQT/p1636471415066500).
> fix: allow chromicons v2 as a peerDependency

- src/components/DayPicker/DayPicker.tsx
**Note**: This PR depends on #224.
**Reviewers**: I would review with **Hide Whitespace Changes** on to see the simple diff.
Adding support for getting the `input` ref of a DayPicker. Combined with `anchorPosition`, this should allow consumers to hack together elegant positioning of the calendar pop-up based on the viewport, etc (until we build it in).
> fix: add support for ref in DayPicker props

- src/components/DayPicker/DayPicker.tsx
Squashing this UI bug.
| - | - |
| ![2021-11-12 10 35 36](https://user-images.githubusercontent.com/14932834/141492865-e7bb3c7d-0cfb-4c9d-849a-43c6f8ed7456.gif) |  ![2021-11-12 10 35 03](https://user-images.githubusercontent.com/14932834/141492911-11105403-01d6-4a84-9af3-fed675032672.gif) |
> fix: make background color of outside selected day transparent

- src/components/Box/Box.test.tsx
- src/components/Box/Box.tsx
I noticed that the component had `flexWrap: boolean`, which I wanted, but it didn't do anything.
> Fix flexWrap on box

- jest.config.js
- package.json
- src/components/Snackbar/Snackbar.test.tsx
- test/mockMuiStyles.js
- yarn.lock
- Upgrade jest, typescript, ts-jest, ts-loader
- Pre-work for getting to https://github.com/lifeomic/chroma-react/issues/37
- Make adjustments based on above upgrades
> deps: Upgrade jest, typescript, ts-jest, ts-loader

- src/components/Slider/Slider.test.tsx
- src/components/Slider/Slider.tsx
- stories/components/Slider/Slider.stories.tsx
> Move slider helper text to always directly follow label

- README.md
- Fix formatted block
- Add `Development` section
> docs: Update/Add documentation

- src/components/IconButton/IconButton.test.tsx
- src/components/IconButton/IconButton.tsx
- stories/components/IconButton/IconButton.stories.tsx
- stories/components/IconButton/default.md
> feat: Add positive and negative `color` values to `<IconButton`

- src/components/Link/Link.test.tsx
- src/components/Link/Link.tsx
- stories/components/Link/Link.stories.tsx
- stories/components/Link/default.md
> feat: Add positive and negative `color` values to `<Link`

- src/components/Text/Text.test.tsx
- src/components/Text/Text.tsx
- stories/components/Text/Text.stories.tsx
- stories/components/Text/default.md
> feat: Add positive and negative `color` values to `<Text`

- src/components/Menu/Menu.test.tsx
- src/components/Menu/Menu.tsx
- src/components/Menu/MenuGroupHeading.tsx
- src/components/Menu/MenuItem.tsx
- src/components/Menu/index.ts
- stories/components/Menu/Menu.stories.tsx
- stories/components/Menu/default.md
I've wanted these for a while. Seems others have too.
This PR also introduces minor sizing changes to `Menu`, per feedback from @dexterca.
> feat: add MenuGroupHeadings

- src/components/Pill/Pill.test.tsx
- src/components/Pill/Pill.tsx
- stories/components/Pill/Pill.stories.tsx
- stories/components/Pill/default.md
> feat: Add negative and positive colors to `<Pill`

- src/components/Menu/Menu.test.tsx
- src/components/Menu/Menu.tsx
- src/components/Menu/MenuItem.tsx
- stories/components/Menu/Menu.stories.tsx
- stories/components/Menu/default.md
> feat: Add color prop to `<MenuItem` 

- src/components/PageLayout/PageLayout.tsx
- src/components/Select/SelectOption.tsx
**Changes**
- Fixed styles from return NAN
> fix: spacing styles

- src/components/TableModule/TableModule.tsx
**Changes**
- Added missing ref type to TableModule
> fix: tableModule add missing ref type

- src/components/Modal/Modal.tsx
**Changes**
- added ellipsis styling to title in Modal
https://user-images.githubusercontent.com/86892478/186480048-2c9bddfa-0e8a-4281-a97e-b628b1e5baca.mov
> fix: added ellipsis to title in Chroma Modal

- jest.config.js
- tsconfig.build.json
Did this to help myself review, since that PR is gigantor
> Ignore stories for coverage, build

- src/components/ExpansionPanel/ExpansionPanel.stories.tsx
- src/components/ExpansionPanel/ExpansionPanel.test.tsx
- src/components/ExpansionPanel/ExpansionPanel.tsx
**Changes**
- Add `leadingIcon` prop
**BEFORE**
**AFTER**
> CHROM-204 ExpansionPanel leadingIcon

- src/components/TableModule/TableModule.tsx
Taking care of Xander's nit from [PR 315](https://github.com/lifeomic/chroma-react/pull/315) in order to trigger the release of v3.7.2
> [NO-JIRA] Flatten nesting in useEffects (new commit to trigger release)

- README.md
> Add docs for Yalc

- .github/workflows/pr-branch-build.yml
- .github/workflows/release.yml
see [`--silent`](https://jestjs.io/docs/cli#--silent)
> Prevent tests from printing messages through the console.
I also plan to upgrade jest to 28.x to pick up built-in [GitHub Actions Reporter
](https://jestjs.io/docs/28.x/configuration#github-actions-reporter)
> ci: improves readability of test results

- src/components/TableModule/TableModule.test.tsx
- src/components/TableModule/TableModule.tsx
- src/components/TableModule/index.ts
- src/components/TableModule/types.ts
This defect was a regression of #341
Added unit tests to cover the code change
> fix: broken getToggleSelectedHandler in TableModule

- src/components/TableModule/TableModule.stories.tsx
- src/components/TableModule/TableModuleRow.tsx
- src/components/TableModule/types.ts
> example on how to manual order row with spinbutton

- src/components/DescriptionList/DescriptionDetails.stories.tsx
- src/components/DescriptionList/DescriptionDetails.tsx
- src/components/DescriptionList/DescriptionDivider.stories.tsx
- src/components/DescriptionList/DescriptionDivider.tsx
- src/components/DescriptionList/DescriptionList.stories.tsx
- src/components/DescriptionList/DescriptionList.test.tsx
- src/components/DescriptionList/DescriptionList.tsx
- src/components/DescriptionList/DescriptionListGroupHeading.stories.tsx
- src/components/DescriptionList/DescriptionListGroupHeading.tsx
- src/components/DescriptionList/DescriptionTerm.stories.tsx
- src/components/DescriptionList/DescriptionTerm.tsx
- src/components/DescriptionList/index.ts
Preliminary PR for adding `<DescriptionList`
Subsequent PRs into feature branch will:
- Add `titleIcon` prop
- Add `termWidth` and `detailsWidth` props
- Add `justify` and `align` props
- Write tests (help wanted)
- Anything else people suggest
In our meeting last week, I originally mentioned a `<CardDetails` component but after giving it more thought, I thought it made more sense to create a `<DescriptionList`. This way, a `<DescriptionList` can exist by itself or inside a `<Paper` component.
---
> feat: Initial commit for adding `<DescriptionList`

- src/components/DescriptionList/DescriptionList.stories.tsx
- src/components/DescriptionList/DescriptionList.tsx
- src/components/DescriptionList/DescriptionListGroupHeading.tsx
> Add title icon to `<DescriptionList`

- src/components/DescriptionList/DescriptionList.stories.tsx
- src/components/DescriptionList/DescriptionList.tsx
> Add `columnsWidth` prop

- src/components/DescriptionList/DescriptionList.stories.tsx
> fix: Fix story keys

- src/components/DescriptionList/DescriptionList.test.tsx
> Improve test coverage

- src/components/DescriptionList/DescriptionDetails.stories.tsx
- src/components/DescriptionList/DescriptionDetails.tsx
- src/components/DescriptionList/DescriptionDivider.stories.tsx
- src/components/DescriptionList/DescriptionDivider.tsx
- src/components/DescriptionList/DescriptionList.stories.tsx
- src/components/DescriptionList/DescriptionList.test.tsx
- src/components/DescriptionList/DescriptionList.tsx
- src/components/DescriptionList/DescriptionListGroupHeading.stories.tsx
- src/components/DescriptionList/DescriptionListGroupHeading.tsx
- src/components/DescriptionList/DescriptionTerm.stories.tsx
- src/components/DescriptionList/DescriptionTerm.tsx
- src/components/DescriptionList/index.ts
- Add `<DescriptionList`, `<DescriptionTerm`, `<DescriptionDetails` and `<DescriptionDivider`
**NOTE**: All changes in this PR have been approved in previous PRs.
> feat: Add `<DescriptionList`

- src/components/Select/ComboBox.stories.tsx
- src/components/Select/ComboBox.test.tsx
- src/components/Select/ComboBox.tsx
> Add support for tooltip message in `<ComboBox`

- src/components/List/List.stories.tsx
- src/components/List/ListItem.tsx
> feat: Add trailing icon for `<ListItem`
