src/components/TableModule/TableModuleRow.test.tsx
src/components/TableModule/TableModuleRow.tsx
stories/components/TableModule/TableModule.stories.tsx

- TableModule `rowActions` can sometimes return `null`.
An example may be like in the story for this PR, where based on the `row` returned, you want to optionally show actions. 
```jsx
<TableModule
rowActions={(row) => {
// Only show actions when carbs are 37 or 67, otherwise,
// we don't want any actionable buttons displayed for this row
if (row.carbs === '37' || row.carbs === '67') {
return actions; // your action buttons go here
}
return null;
}}
/>
```
Currently, on master, the above example would yield you an empty toolbar:
This change does what you'd expect - if `rowActions` returns `null`, a toolbar will not be displayed at all

FIX: rowActions return null shouldnt render bubble

---

.github/workflows/release.yml

- Attempt to only run the release step when a tag is available
Looking at the last merge to master (without a tag), https://github.com/lifeomic/chroma-react/runs/1161223504?check_suite_focus=true, it still attempted to publish to npm.   I'm hoping this will only attempt to publish to NPM and cut a release if the last commit has a tag.  I looked at https://stackoverflow.com/questions/58475748/github-actions-how-to-check-if-current-push-has-new-tag-is-new-release as a reference.

FIX: Adjust release workflow

---

src/components/Box/Box.test.tsx
src/components/Box/Box.tsx

**Changes**
- Added `flex-end` and `flex-start`
- Right now we are setting `flex-end` to `align-items: end` when I think we should allow for both being an option to pass in. 
Ex issue: 
- Before when I passed in `align="flex-end"`
- After when I passed in `align="flex-end"`

CHROM add flex-start and flex-end

---

src/components/Select/Select.tsx
stories/components/ComboBox/ComboBox.stories.tsx

Issue: when you have multiple options with long display values, the top selection gets cut off.
**Changes**
- Fixed display value for select and comboBox button styles
- Added more options with longer text
**BEFORE:**
**AFTER**:

Bugfix - ComboBox multi selection cuts off

---

src/components/Modal/Modal.test.tsx
src/components/Modal/Modal.tsx
stories/components/Modal/Modal.stories.tsx
stories/components/Modal/default.md

See [this Slack thread](https://lifeomic.slack.com/archives/CHMFL4PQT/p1602771468011800).
- Added the `disableDismissOnClickOutside` prop to the `Modal` component, to disable automatic dismissal on clicking the overlay.
- Updated tests + docs around the new prop.
- Added a hard-coded test ID for the overlay component to support unit tests.
- I couldn't think of an idiomatic way to find that component / execute the click without this. If there's a better alternative to exporting that ID, 100% open to suggestions!

Add disableDismissOnClickOutside prop to Modal

---

src/components/TableModule/TableHeaderCell.tsx
src/components/TableModule/TableModuleCell.test.tsx
src/components/TableModule/TableModuleCell.tsx

This PR allows for last column table content to be left-aligned. Last column content will continue to default to right-aligned.
BEFORE | AFTER
-- | --

FIX: Allow left align override on last column header and cell

---

src/components/Modal/Modal.tsx

Gif shows the issue. When a parent has border radius, it needs overflow hidden to ensure child content doesn't exceed the corners.

Add overflow hidden to ensure content doesn't go outside rounded corners

---

src/components/SlideOver/Header.test.tsx
src/components/SlideOver/Header.tsx
stories/components/SlideOver/SlideOver.stories.tsx
stories/components/SlideOver/default.md

- @derrh is wanting to render an avatar + name in the header rather than the `title`.  This should allow him to do what he needs.
I think your code would look something like the storybook example:
```jsx
<Header>
<Avatar name="Tony" src={path-to-some-img-url-for-the-avatar} />
<Text>Tony Ward</Text>
</Header>
```
If you want some better spacing between the avatar and text, may need a wrapping `<div />` and apply a class to it.
```jsx
<Header>
<div className="some-spacing-class">
<Avatar name="Tony" src={path-to-some-img-url-for-the-avatar} />
<Text>Tony Ward</Text>
</div>
</Header>
```
**NOTE:** Since this is making a prop go from required, to not-required, I'm still going to upgrade with `patch`.  Let me know if this warrants a `minor` in your mind though.   If I was going from …

FEAT: Add children to SliderOver Header

---

src/components/Stepper/Step.tsx
stories/components/Stepper/Stepper.stories.tsx
stories/components/Stepper/default.md

I think this could come in handy during prototyping and playing around, not having to worry about providing Icons, and also maybe in some places an Icon just doesn't make sense though mixing the two options probably would not work great

Allow for icon being optional in Step defaulting to number position

---

src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Radio/RadioGroup.test.tsx
src/components/Radio/RadioGroup.tsx
src/components/Radio/RadioGroupMinimal.test.tsx
src/components/Radio/RadioGroupMinimal.tsx
src/components/Select/ComboBox.tsx
src/components/Select/Select.tsx
src/components/TextArea/TextArea.test.tsx
src/components/TextArea/TextArea.tsx
src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx
src/components/Toggle/Toggle.test.tsx
src/components/Toggle/Toggle.tsx
src/styles/screenreaderOnly.ts
stories/components/Checkbox/Checkbox.stories.tsx
stories/components/ComboBox/ComboBox.stories.tsx
stories/components/Radio/Radio.stories.tsx
stories/components/Select/Select.stories.tsx
stories/components/TextArea/TextArea.stories.tsx
stories/components/TextField/TextField.stories.tsx
stories/components/Toggle/Toggle.stories.tsx

- Enforce `aria-label` as a prop if a `label` or `title` is not provided
- Apply a class that hides the label/title elements from the user, but still accessible via screenreaders
**This is a breaking change**, but is important for accessibility. I pitched this in the Chroma channel and sounded like it was well received 👍 - (let me know if I left someone out on the PR)

a11y: Enforce aria-label if no label/title

---

src/components/Select/ComboBox.test.tsx
src/components/Select/ComboBox.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
stories/components/ComboBox/ComboBox.stories.tsx
stories/components/ComboBox/default.md
stories/components/Select/Select.stories.tsx
stories/components/Select/default.md

Wanted to add suport for `secondaryLabel` for `Select` and `ComboBox` components to help facilitate some figma designs.
https://www.figma.com/file/I9QFAEnOHpurBdOHHUP6y7/PHC-Designs?node-id=3348%3A0

Support secondaryLabel for Select and ComboBox components

---

src/components/TableModule/TableHeaderCell.test.tsx
src/components/TableModule/TableHeaderCell.tsx

**Changes**
- Updated table header tag from `th` to `td` if no header content or label is provided.
- Followed recommended "How to fix": `If the cell is not a header or must remain empty (such as the top-left cell in a data table), make the cell a <td> rather than a <th>`

PHC-463 Table Header

---

src/components/Checkbox/Checkbox.test.tsx
src/components/Checkbox/Checkbox.tsx
src/components/Radio/Radio.test.tsx
src/components/Radio/Radio.tsx
src/components/SearchField/SearchField.test.tsx
src/components/SearchField/SearchField.tsx
src/components/Select/ComboBox.test.tsx
src/components/Select/ComboBox.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
src/components/TextArea/TextArea.test.tsx
src/components/TextArea/TextArea.tsx
src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx
src/components/Toggle/Toggle.test.tsx
src/components/Toggle/Toggle.tsx
src/components/_private/forms/FormElementUtils.ts

**Changes**
- Conditionally add `aria-describedBy` attribute if `hasError` or `helpMessage`.

PHC-463 Select aria-describedby

---

src/components/Select/Select.tsx

**Changes**
- Updated ComboBox selected chip color from `primary[600]` (#0096e1) to `primary.main` (#0096e1). 
- **They are the same color** but this will allow me to override this color in other apps by changing the main color in the palette. 
**BEFORE**
**AFTER**

PHC-463 ComboBox chip color

---

src/components/ButtonLink/ButtonLink.tsx

Issue:  Bootstrap styles override button color set in root styles when hovering on `ButtonLink`. 
**Changes**
- Added `color: white` when hovering over button
**BEFORE**
**AFTER**

PHC-463 Button Link hover

---

src/components/Menu/Menu.test.tsx
src/components/Menu/Menu.tsx

**Issue**: passing in `disabled` prop into `MenuItem` doesn't disable item.
**Changes**
- Spreading menu item props
**BEFORE:**
**AFTER:**

Menu - menu item props

---

src/components/Text/Text.tsx
src/components/Tooltip/Tooltip.tsx
src/styles/__snapshots__/createTheme.test.ts.snap
src/styles/createTypography.ts

Improve tooltip legibility

---

src/components/Text/Text.tsx

Map text sizes to font sizes where it makes sense.
BEFORE | AFTER (No visual changes expected)
-- | --

Map text sizes to font sizes

---

src/components/Popover/Popover.tsx

Fixes a bug where if popover is a child of a div with `color: white` (or other non-contrasting text with it's white background), the text is not visible. Since it sets the background explicitly to white, it should also set the text color.
Bug in action:

Set text color of popover to primary to complement background color

---

src/components/Select/GroupHeading.test.tsx
src/components/Select/GroupHeading.tsx
src/components/Select/Select.test.tsx
src/components/Select/Select.tsx
stories/components/Select/Select.stories.tsx
stories/components/Select/groupHeading.md

The built code loses the `type` attribute information. Using a
data-* attribute is preserved across the build.

WELL-706 - Fix GroupHeading rendering

---

src/components/ButtonFilePicker/ButtonFilePicker.tsx

**Changes**
- Updated a few `<Button` hover colors from primary `800` -> `900`
**BEFORE**
**AFTER**

A11y ButtonFilePicker

---

src/components/ButtonLink/ButtonLink.tsx

**Changes**
- Updated a few `<Button` hover colors from primary `800` -> `900`
**BEFORE**
**AFTER**

A11y ButtonLink

---

src/components/Checkbox/Checkbox.tsx
stories/components/Checkbox/Checkbox.stories.tsx

Add contrast to checkbox-primary, checkbox-emphasis and tick mark stroke
NOTE: Top-left checkbox is hover state
BEFORE | AFTER
-- | --

a11y Checkbox

---

src/components/Radio/RadioGroupMinimal.tsx
stories/components/Radio/Radio.stories.tsx

- Improve color contrast for Radio Group Minimal
- Fix broken demo in Radio Group and Radio Group Minimal stories
- Make Radio Group Minimal legend behavior and style match Radio Group legend (support inverse legend)
BEFORE | AFTER | &nbsp;
-- | -- | --

a11y Radio group minimal color contrast and story updates

---

src/components/_private/forms/FormErrorMessage.tsx

Improve contrast for form error messages
**RELATED PR**: [Update secondary (green) and error (red) palettes](https://github.com/lifeomic/chroma-react/pull/90)
BEFORE | AFTER
-- | --

a11y Form error message contrast

---

src/components/TextArea/TextArea.tsx

NOTE: Couldn't show invalid warnings in BEFORE screenshot below because https://github.com/lifeomic/chroma-react/issues/97 was lighting up the screen with warnings as well.
BEFORE | AFTER
-- | --

a11y TextArea contrast

---

src/components/Toggle/Toggle.tsx

No a11y checks were failing here but styles need to be consistent with other form components.
BEFORE | AFTER
-- | --

Toggle contrast

---

src/components/Checkbox/Checkbox.tsx
src/components/Radio/Radio.tsx
src/components/Radio/RadioGroupMinimal.tsx

Make Checkbox and Radio inverse backgrounds consistent with other form components
NOTE: This change is very subtle visually.
BEFORE | AFTER
-- | --

Checkbox and Radio inverse background

---

src/components/ButtonFilePicker/ButtonFilePicker.tsx

- Fix ButtonFilePicker dead cursor area
- https://developer.mozilla.org/en-US/docs/Web/CSS/::file-selector-button
https://user-images.githubusercontent.com/8069555/111808705-a2ad0d00-88aa-11eb-8793-0f32176aa95c.mov
https://user-images.githubusercontent.com/8069555/111808739-ab9dde80-88aa-11eb-96c1-9256fa5e12aa.mov

fix: ButtonFilePicker cursor dead area

---

src/components/DotLoader/DotLoader.tsx

Changing green here to get it closer to the original green used before `palette.green` shift
BEFORE | AFTER
-- | --

Change green on DotLoader

---

src/components/Pill/Pill.tsx

Gradient seems a bit too harsh after `primary.main` color shift. Softening the highlight effect in this PR.
BEFORE | AFTER
-- | --

Soften gradient of highlight pill

---

src/components/TableModule/TableHeaderCell.tsx

This bug revealed itself when we went to `td` for empty table header cells instead of `th` for a11y reasons.
BEFORE | AFTER
-- | --
The last (far-right) columns' table headers have extra right padding  ![screencapture-localhost-9001-iframe-html-2021-03-31-10_32_27](https://user-images.githubusercontent.com/485903/113162145-06212e00-920d-11eb-839d-ff1fc80a6da1.png) | ![screencapture-localhost-9001-iframe-html-2021-03-31-10_31_00](https://user-images.githubusercontent.com/485903/113162143-04f00100-920d-11eb-9dfe-7e4517a8065f.png)

Align first and last column table headers

---

src/components/Modal/Modal.tsx

With the addition of `overflow: 'hidden'` the modal actions can
be clipped on small screens.

WELL-933 - Don't hide modal actions

---

src/components/PrimaryNavigation/PrimaryNavigation.tsx

This fixes the following failure with FastPass automated check:
_ARIA attribute is not allowed: aria-checked="false"_
Closes #114

Add checkbox role to toggle sidebar button

---

src/components/Modal/Modal.tsx

Modal footer was being hidden on short viewports. This PR flexes modal form height.
&nbsp; | BEFORE | AFTER
-- | -- | --
Short desktop viewport | <img width="681" alt="01-Screen Shot 2021-04-27 at 12 00 07 PM" src="https://user-images.githubusercontent.com/485903/116274634-d8b69a00-a750-11eb-9ca6-f4697c2af771.png"> | <img width="681" alt="Screen Shot 2021-04-27 at 12 00 12 PM" src="https://user-images.githubusercontent.com/485903/116274641-d9e7c700-a750-11eb-8281-f6fe84ef7a4a.png">
Short mobile viewport | <img width="402" alt="Screen Shot 2021-04-27 at 12 03 13 PM" src="https://user-images.githubusercontent.com/485903/116274643-d9e7c700-a750-11eb-8e6a-1c18034ce201.png"> | <img width="402" alt="Screen Shot 2021-04-27 at 12 03 20 PM" …

Flex modal form height

---

src/components/Modal/Modal.tsx

Transitioning scale on opening / closing of `fullScreen` modal is pretty sluggish, especially on larger screens.
- Remove `scale` from full screen modal transition
- Remove `shouldReduceMotion` from full screen modal transition since we're only changing opacity
https://user-images.githubusercontent.com/485903/116299501-c7c75200-a76b-11eb-92c6-ec71f696fe92.mov
https://user-images.githubusercontent.com/485903/116299504-c8f87f00-a76b-11eb-9dd4-7543b308edc7.mov

Remove scale from full screen modal opening/closing transition

---

stories/components/Select/default.md
stories/components/Select/selectOption.md
stories/components/Select/selectedOptionDisplay.md

**Changes**
- Added `disabled` property to storybook documentation for `Select`.
Was missed in this [PR](https://github.com/lifeomic/chroma-react/pull/131#pullrequestreview-669409058).

Select - documentation update

---

src/components/TableModule/TableModule.tsx
src/components/TableModule/types.ts

Adding the capability to specify a generic type for TableModule configuration types, in a non-breaking way.
I _think_ this is correct, but would love confirmation from someone more knowledgeable.

Make table configuration types generic over an Item

---

package.json
src/components/NumberFormat/PhoneNumberFormatField.test.tsx
src/components/NumberFormat/PhoneNumberFormatField.tsx
src/components/NumberFormat/UnitNumberFormatField.test.tsx
src/components/NumberFormat/UnitNumberFormatField.tsx
src/components/NumberFormat/index.ts
src/styles/overrides/ChromaOverrides.ts
yarn.lock

This adds the number input fields from https://github.com/lifeomic/connect-web-console/blob/master/src/elements/Form/NumberFormats.test.tsx. All the tests are included as well, with minor changes due to the different testing library.
These input fields are useful for multiple projects, including `wellness-admin-app`.

Add number format inputs from connect-web-console

---

src/components/ColorPicker/ColorPicker.tsx

- Use grid layout for swatches
- Horizontally center swatch group within popover
- Use pseudo element for bottom border
- Right align swatch in input
- Reduce border radius of square swatch
- Remove min width of popover
BEFORE | AFTER
-- | --

Use grid layout for ColorPicker swatches

---

src/components/NumberFormat/UnitNumberFormatField.test.tsx
src/components/NumberFormat/UnitNumberFormatField.tsx

This changes the `PriceFormatField` props of `min`, `max`, `value`, `onChange` to deal with values in terms of integer penny amounts instead of decimal dollar amounts. The underlying `UnitNumberFormatField` still uses decimal numbers because it should be able to handle anything, but this should be hidden away when dealing with money that only ever deals with integer penny amounts.
This is motivated by a desire to standardize dealing with money using pennies, to remove confusion and the need for converting when interfacing with API's that expect penny amounts. This is technically a breaking change, but since I don't believe anyone else is using this yet, hopefully making this change now will prevent confusion in the future.

Convert PriceFormatField to use penny values

---

src/components/ColorPicker/ColorPicker.tsx

I was getting annoyed with outline while using mouse. We use this + a polyfill for older browser to get accessible buttons for keyboard-users. Users will not see these styles unless they use their keyboard to focus the element
&nbsp; | BEFORE | AFTER
-- | -- | --
Mouse user | ![before-mouse](https://user-images.githubusercontent.com/485903/123020260-0b22f300-d3a0-11eb-9f67-09fb1c0c5cd7.gif) | ![after-mouse](https://user-images.githubusercontent.com/485903/123020272-0eb67a00-d3a0-11eb-88a0-33f3d7183276.gif)
Keyboard user | ![before-keyboard](https://user-images.githubusercontent.com/485903/123020321-1ece5980-d3a0-11eb-82c4-11fc3ee1aee9.gif) | ![after-keyboard](https://user-images.githubusercontent.com/485903/123020340-242ba400-d3a0-11eb-9172-05ae2304f10b.gif)

Remove outline for mouse users / Add outline for keyboard users

---

src/components/ColorPicker/ColorPicker.tsx
src/components/ColorPicker/index.ts

**Changes**
- Set width on popover to prevent fullWidth ColorPickers popover from stretching
- Exported `isValidHexColor` helper function to use in PHC for form validation
**BEFORE**
**AFTER**

ColorPicker fullWidth popover

---

package.json
src/components/Chip/Chip.tsx
src/components/ExpansionPanel/ExpansionPanel.tsx
src/components/Modal/Modal.tsx
src/components/PrimaryNavigation/PrimaryNavigationExpansionItem.tsx
src/components/Select/ComboBox.tsx
src/components/Select/Select.tsx
src/components/SlideOver/Header.tsx
src/components/Snackbar/Snackbar.tsx
src/components/TableModule/TableHeaderCell.tsx
src/components/TableModule/TableModuleRow.tsx
yarn.lock

- Use Chromicons internally instead of the now deprecated, internal icons (https://github.com/lifeomic/chroma-react/pull/143)

FEAT: Add chromicons and use them over internal icons

---

src/components/Select/Select.tsx

When ComboBox had a single line of chips, the height of the parent wrapper would increase by 1px once a chip(s) would appear.
**BEFORE WITHOUT CHIPS** | **BEFORE WITH CHIPS** | **AFTER WITHOUT CHIPS** | **AFTER WITH CHIPS**
-- | -- | -- | --
`height: 35px` (computed) | `height: 36px` (computed) | `height: 35px` (computed) | `height: 35px` (computed)
One side effect of this change is that chips are no longer perfectly centered vertically. In other words there is one pixel more of padding at the bottom of the chip list than at the top of the chip list (as seen below). So the trade off here is the height of the `<Select` will no longer shift in height once a chip appears but the chips are no longer vertically centered. 😢

Adjust margins so single line of chips does not affect ComboBox height

---

CONTRIBUTING.md

Addressing this feedback: https://github.com/lifeomic/chroma-react/pull/149#pullrequestreview-697569743.
How I created this file:
- Copied [the `CONTRIBUTING.md` from `phc-sdk-py`](https://github.com/lifeomic/phc-sdk-py/blob/master/CONTRIBUTING.md), another of our open-source repos.
- Slimmed it down significantly, since I wasn't sure if most of the details there applied to this repo.
- Added details about `semantic-release`.

chore: add CONTRIBUTING.md to call out semantic-release requirement

---

src/components/PageLayout/PageLayout.test.tsx
src/components/PageLayout/PageLayout.tsx
stories/components/PageLayout/applyBackground.md

**Changes**
- Added `backgroundImage` prop to PageLayout
- It can be overridden at a theme level but we should also allow one time overrides

FIX: add backgroundImage prop to PageLayout

---

src/components/Select/Select.tsx

Some consumers have concerns that the `maxHeight` of the `<Select` popover is too small. There are probably a couple different ways to solve this but this seemed the most simplistic since most mobile devices are taller than 328px.
If anyone has any other ideas I'm open to other options.
The complaint we are getting is that with rating-type questions that require ten or more options, the user might think the ratings stop at four when in fact options go up to ten. 
BEFORE | AFTER
-- | --

fix: increase Select maxHeight to 328px

---

src/styles/makeStyles.ts

Motivation: Typescript 4 makes the type inference on `props` more strict, and where the type of props cannot be strictly inferred, consumers must add a a type parameter to satisfy makeStyles. Some do `makeStyles<{}>(...)` `makeStyles<Record<string, string>>(...)` or `makeStyles<uknown>()` for simplicity. Adding a default type ([matching the types in mui](https://github.com/mui-org/material-ui/blob/v4.12.1/packages/material-ui-styles/src/makeStyles/makeStyles.d.ts#L12)) makes this unnecessary for consumers upgrading to TS 4.x

Add a default type on makeStyles

---

jest.config.js
src/components/NumberFormat/PhoneNumberFormatField.tsx
stories/components/NumberFormat/PhoneNumberFormatField.stories.tsx
stories/components/NumberFormat/phoneNumberFormat.md
test/emptyMock.js

- Add `import 'react-phone-number-input/style.css';` to resolve the styling issues with `<PhoneNumberFormatField />`
- After adding this, I had to add a `moduleNameMapper` for CSS files for jest.  I created an `emptyMock`, in case we need to reuse that pattern for something else in the future.
- Wrote (brief) docs for component

fix: Import CSS for PhoneNumberFormatField + docs

---

src/components/Text/Text.test.tsx
src/components/Text/Text.tsx
stories/components/Text/Text.stories.tsx
stories/components/Text/default.md

- Add `align` prop to `<Text`
- Currently only supporting the three I'm most aware of, `center`, `left`, `right`, and `justify`.  Can add more if folks use other options more frequently. https://developer.mozilla.org/en-US/docs/Web/CSS/text-align
I made this a `fix` conventional commit to do the `PATCH` version.

fix: Add "align" to Text component

---

stories/components/Alert/Alert.stories.tsx
stories/components/Button/Button.stories.tsx
stories/components/ButtonFloat/ButtonFloat.stories.tsx
stories/components/ButtonLink/ButtonLink.stories.tsx
stories/components/ButtonUnstyled/ButtonUnstyled.stories.tsx
stories/components/Divider/Divider.stories.tsx
stories/components/IconButton/IconButton.stories.tsx
stories/components/IconButtonFloat/IconButtonFloat.stories.tsx
stories/components/IconButtonLink/IconButtonLink.stories.tsx
stories/components/IconTile/IconTile.stories.tsx
stories/components/Icons/Icons.stories.tsx
stories/components/LayoutManager/LayoutManager.stories.tsx
stories/components/Menu/Menu.stories.tsx
stories/components/Select/Select.stories.tsx
stories/components/TableModule/TableModule.stories.tsx
stories/components/TextArea/TextArea.stories.tsx
stories/components/TextField/TextField.stories.tsx

- Gearing up to strip out the icons from this library, I migrated the storybook stories from the internal icons to Chromicons

docs: use chromicons over internal icons

---

src/components/Checkbox/Checkbox.tsx

Here is an [issue](https://github.com/framer/motion/issues/262) that I was able to reference.
**BEFORE**
https://user-images.githubusercontent.com/32574227/126359499-847062ec-ac1a-447c-a77f-76390b179753.mov
**AFTER**
https://user-images.githubusercontent.com/32574227/126359548-19bdbf86-f643-43fa-ae23-74778f0633ee.mov

fix: checkbox disabled state styles

---

src/components/TextField/TextField.test.tsx
src/components/TextField/TextField.tsx
stories/components/TextField/TextField.stories.tsx
stories/components/TextField/default.md

**Changes**
- Added `startAdornment` and `endAdornment` as new props

feat: add start and end adornments to TextField

---

stories/components/TextField/TextField.stories.tsx
stories/components/TextField/default.md

- Add `aria-hidden` to adornment icons for a11y.  Sorry, I should've caught this first time around.
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute
- https://stackoverflow.com/questions/61048356/why-do-we-use-aria-hidden-with-icons
- https://www.w3.org/WAI/GL/wiki/Using_aria-hidden%3Dtrue_on_an_icon_font_that_AT_should_ignore

docs: Add `aria-hidden` to adornment icons

---

src/styles/overrides/ChromaOverrides.ts

This PR exports RadioGroupMinimal styles for override. When the selected state has a light background color, there needs to be a way to make the selected state text color darker to improve contrast for a11y.
Here is an example of what I'm trying to fix with this PR. Right now, there is no way to override the font color of _Landscape_ in Chroma. _Landscape_ needs to be a darker color to pass a11y checks.

fix: Export `<RadioGroupMinimal` styles for override

---

src/components/Radio/RadioGroup.tsx
src/components/Radio/RadioGroupMinimal.tsx

When adding a `RadioGroupMinimal` to my project I noticed the text label (`<legend>`) was missing. Removing `position: relative` from the root (`<fieldset`) made the text label appear. I took a look at both `<RadioGroup` and `<RadioGroupMinimal` and from what I can tell I don't think `position: relative` is needed. Removing relative positioning didn't seem to have any visual changes in stories across Chrome, Firefox and Safari.
@ynotdraw can you confirm if we need relative positioning or not? These components are leveraging `<fieldset>` and `<legend>` so there might be something I'm missing. 
RELATIVE POSITION / LABEL HIDDEN | POSITION UNSET / LABEL VISIBLE
-- | --

fix: Remove relative position of both radio groups' root (fieldset)

---

src/components/Radio/RadioGroupMinimal.test.tsx
src/components/Radio/RadioGroupMinimal.tsx
stories/components/Radio/Radio.stories.tsx
stories/components/Radio/radioGroupMinimal.md

Adding `fullWidth` prop so that by default `<RadioGroupMinimal` doesn't span 100% width of parent. When there was only a couple of radio options, the design looked a little wonky on account of options being spread to extreme left and right when `direction` was set to `row`.
BEFORE | AFTER (default) | AFTER (fullWidth)
-- | -- | --
**UPDATED DOCS**
**UPDATED KNOBS**
`direction="row"` | `direction="column"`
-- | --
Closes #213

fix: Add `fullWidth` prop to `<RadioGroupMinimal`

---

README.md
src/components/DayPicker/DayPicker.test.tsx
src/components/DayPicker/DayPicker.tsx

Addressing three promised follow-ons from #215:
1. Adding a README note re: CSS loaders.
2. Better keyboard navigation in the `DayPicker` component (`TAB` + `ESC` support).
3. Better tests for the custom rendering props of `DayPicker`.
- Elegant anchor behavior
- Fix squashing in small size scenarios

fix: better DayPicker keyboard navigation support

---

src/components/DayPicker/DayPicker.tsx
src/components/Modal/Modal.tsx
src/components/Modal/helpers.ts
src/utils/event-handlers.ts
src/utils/index.ts

**Note**: This PR depends on #216.
Consolidating the event handlers "forwarding" behavior shared by `DayPicker` and `Modal` into a single `composeEventHandlers` helper.
I put this in a more conspicuous import path, since I thought it might be useful to external consumers.
Also, deprecated (and `istanbul ignored`) the internal `wrapEvent` helper from `Modal`.

feat: add `composeEventHandlers` helper

---

src/components/Avatar/Avatar.test.tsx
src/components/Avatar/Avatar.tsx
stories/components/Avatar/Avatar.stories.tsx
stories/components/Avatar/default.md

Sometimes, avatar images fail to load, and causes layout issues.
Example: 
This `img` src fails to load because it's set to my google profile image, but my cookie for google auth has expired. It causes overflow and horizontal scroll on the whole page. 
Just emit an error to consumer (if they want it) and fallback to initials, hiding the failed `img` tag.

Add an onError handler to avatar img

---

src/components/KeymapHelp/KeymapHelp.test.tsx
src/components/KeymapHelp/KeymapHelp.tsx
src/components/Select/useWindowSize.ts
stories/components/KeymapHelp/KeymapHelp.stories.tsx
stories/components/KeymapHelp/default.md

Something weird: the `master` build in GitHub Actions is claiming 85% branch coverage, but my local runs are claiming <80 (causing failure).
Doesn't seem like an urgent issue since the master build is continuously passing, but thought I'd fixup a couple files that were bringing us down.
I fixed two problems:
- No existing test files or storybookfor the `Keymap` component. I added a dead-simple test and a storybook entry.
- I wonder if this is worth keeping around in Chroma. It adds a dependency, and [there is only one use case in the whole org](https://github.com/search?q=org%3Alifeomic+KeymapHelp&type=code).
- An unused `useWindowSize` hook that I deprecated and `istanbul ignore`d.
- Why it's dead: there's an identical hook located at a more friendly filepath …

Test coverage cleanups

---

src/components/DayPicker/DayPicker.tsx
stories/components/DayPicker/default.md

Adding very basic manual control of anchor positioning in `DayPicker` via an `anchorPosition` prop. Maybe in the future, this component could support elegant auto-positioning based on viewport collisions, etc.
I'm hoping that this will suffice for a while, and that individual consumers who need that kind of elegant behavior can implement it themselves until we have time to add it to Chroma (I know that at least a couple initial consumers can live without fancy automatic adjustments for now).
In order, shows:
- bottom-left (default)
- bottom-right
- top-right (note the poor behavior with viewport collisions -- it's currently on developers to pick a sane direction)
- top-left

fix: add anchorPosition prop to DayPicker

---

src/components/DayPicker/DayPicker.test.tsx
src/components/DayPicker/DayPicker.tsx
stories/components/DayPicker/DayPicker.stories.tsx
stories/components/DayPicker/default.md

Two:
1. Adding a mechanism to specify a min/max date, as well as selectively disabling dates arbitrarily.
2. Allow specifying arbitrary props to the internal day picker, to allow more flexible customization.

fix: add min/max support to DayPicker

---

src/components/DayPicker/DayPicker.tsx

Master build is failing since its a new month and the calendar isn't opening to the selected month by default. I'm guessing this was the expected behavior judging from the tests.

fix: open day picker to currrently selected month by default

---

stories/components/FormBox/FormBox.stories.tsx

Makes `<FormBox` demo a little prettier with `<RadioGroupMinimal fullWidth`
BEFORE | AFTER
-- | --

docs: Update FormBox demo with fullWidth RadioGroupMinimal

---

src/components/ButtonLink/ButtonLink.tsx

BEFORE | AFTER
-- | --
Closes #234

fix: Center align text in `<ButtonLink`

---

src/components/Box/Box.test.tsx
src/components/Box/Box.tsx
stories/components/Box/Box.stories.tsx
stories/components/Box/default.md

I find myself declaring `'& > *': { flex: 1 }` a lot with `<Box` to make children fill parent container so I thought of adding this prop as a quick way to accomplish this.
https://user-images.githubusercontent.com/485903/151193473-518ddc0b-46f1-4c5c-94f5-22832ce1350a.mov
Closes #242

feat: Add flexChildren prop

---

src/components/Radio/Radio.tsx
stories/components/Radio/radioGroupMinimal.md

This display bug doesn't appear in Storybook but surfaced when I consumed the latest Chroma changes from another repo.
BEFORE | AFTER | &nbsp;
-- | -- | --

fix: `<RadioGroupMinimal` tooltip display

---

README.md

This PR only add spaces to the beginning of each line. It does not change any text or formatting. (Repeat of earlier cancelled PR and deleted branch)
The step numbering currently appears correctly on github, but is reset to all 1s when automatically imported into phc-docs at https://docs.dev.lifeomic.com/development/open-source/chroma-react/. I believe this is due to the python-markdown used by phc-docs interpreting the .md file differently than the GitHub-flavored-Markdown of Github. Specifically, python-markdown thinks the consecutive list is restarting at 1 (despite the 2 or 3 in the text) when there is no spacing at the lines between the numbered steps. Adding two tabs at each line seems to fix this.

docs: Change spacing to correct numbering on doc site

---

src/components/TableModule/TableModule.tsx

fix: Text alignment for text buttons in table module actions

---

.storybook/manager-head.html

Another attempt at getting favicon to display properly on GH pages.
https://stackoverflow.com/questions/46163065/github-pages-website-favicon-not-showing

fix: another attempt to display favicon

---

src/components/ButtonLink/ButtonLink.test.tsx
src/components/ButtonLink/ButtonLink.tsx
stories/components/ButtonLink/ButtonLink.stories.tsx

No docs update for this PR since we state: 
_An element that appears as a Button component, but is a link. It has the same properties as Button_.

feat: Add positive and negative `color` values to `<ButtonLink`

---

src/components/IconButtonLink/IconButtonLink.test.tsx
src/components/IconButtonLink/IconButtonLink.tsx
stories/components/IconButtonLink/IconButtonLink.stories.tsx

No docs update for this PR since we state:
_An element that appears as an Icon Button component, but is a link underneath the covers. It has the same properties as Icon Button exposed._

feat: Add positive and negative `color` values to `<IconButtonLink`

---

src/components/DayPicker/DayPicker.tsx

Add fixed width to day picker container so we don't get ovals for day hover/focus/selected states when a day picker isn't `fullWidth`
BEFORE | AFTER
-- | --

fix: Add fixed width to day picker

---

src/components/DayPicker/DayPicker.tsx

Use palette for day background hover color vs. default `react-day-picker` color
BEFORE | AFTER
-- | --

fix: Use palette for `<DayPicker` background hover color

---

src/components/DayPicker/DayPicker.tsx
stories/components/DayPicker/DayPicker.stories.tsx
stories/components/DayPicker/default.md

This PR locks down `<DayPicker`'s `pickerColor` to two palette options: `primary` (default) and `secondary`. Text color of `pickerColor` for each option will now pull from `getContrastText`.
`pickerColor` is replacing `selectedBackgroundColor`.
AFTER (PRIMARY) | AFTER (SECONDARY)
-- | --

feat: Add `DayPicker` selected day background color from palette options

---

src/components/Stepper/Step.tsx
src/components/Stepper/Stepper.test.tsx
src/components/Stepper/Stepper.tsx

Closes #44 
**Issue**
- Visual impaired users have no way of know which step is the active step
- There are no focus styles when tabbing (we only have hover styles)
- Steps as `div` have no tabIndex so they are missed in the tab order
**Changes**
- Fixed syntax to be more semantic (`ol` & `li`) 
- Added focus styles to steps
- Added `tabIndex` to active `div` steps
- Button steps already have a `tabIndex` with the button element
- Added `aria-label` to read active step index of out total number of steps
- Added `aria-describedBy` so screen readers can get title, subTitle, and subTitlePill values
**BEFORE**
https://user-images.githubusercontent.com/32574227/176944194-9135f19c-ca4b-464c-a36a-0dc948ea35bc.mov
**AFTER**
https://user-images.githubusercontent.com/32574227/176944173-af03c65f-dd6e …

Fix stepper accessibility 

---

src/components/Button/Button.tsx
src/components/ButtonFilePicker/ButtonFilePicker.tsx
src/components/ButtonLink/ButtonLink.tsx
src/components/ColorPicker/ColorPicker.tsx
src/components/Divider/Divider.tsx
src/components/Header/Header.tsx
src/components/IconButton/IconButton.tsx
src/components/IconTile/IconTileBadge.tsx
src/components/IconTile/IconTileHero.tsx
src/components/Link/Link.tsx
src/components/Menu/MenuItem.tsx
src/components/Modal/Modal.tsx
src/components/Pill/Pill.tsx
src/components/Popover/PopoverItem.tsx
src/components/Radio/Radio.tsx
src/components/Radio/RadioGroupMinimal.tsx
src/components/SearchField/SearchField.tsx
src/components/Select/RoverOption.tsx
src/components/Select/Select.tsx
src/components/Skeleton/Skeleton.tsx
src/components/Slider/Slider.tsx
src/components/Stepper/Step.tsx
src/components/Tabs/TabList.tsx
src/components/TextArea/TextArea.tsx
src/components/TextField/TextField.tsx
src/components/Toggle/Toggle.tsx
src/styles/createTheme.ts
src/styles/utils/colorManipulator.ts
stories/storyComponents/LabeledInput.tsx

- Replaced all usage of rgba(x, y, z, a) with hexToRgba('some color', a)
- This allows us to use theme colors from various palettes to keep things consistent and easier to change
- I went ahead and changed some additional hex colors to use palettes
- This PR can be an example to anyone who wants to start using the hexToRgba util in other repos
- I searched for rgba() in VSCode
- I left test files alone, as well as boxshadows since they were declared outside of a component. If you'd like me to address these as well, I can.
- let me know if I missed any refs!

CHROM 199 Update rgba to hexToRgba()

---

src/components/TextField/TextField.tsx
stories/components/TextField/TextField.stories.tsx

- Added a left-aligned red asterisk to TextField to show that a field is required
- @HaleyWardo pointed out that the 'required' prop may be confused for validation. Can I get thoughts on a solution?
- Idea: Change to "styleRequired" or similar
- Idea: Add docs note that this is just visual and validation still needs to be done

PW-96 Add Required Styling to TextField

---

README.md
src/styles/__snapshots__/createTheme.test.ts.snap
src/styles/createPalette.ts
src/styles/index.ts
src/styles/overrides/index.ts
src/testUtils/renderWithTheme.tsx
stories/components/Paper/Paper.stories.tsx
stories/decorators/withTheme.tsx
stories/styles/color/color.stories.tsx
stories/styles/theme/default.md
stories/styles/theme/theme.stories.tsx

**Changes**
- Updated component props and styling to previous values so that no breaking changes are introduced
- Added `StyledEngineProvider` export and updated documentation
- This provider is required in order for our styles to override the MUI emotion component styles

fix: MUI component overrides and styling injection

---

src/components/TextArea/TextArea.tsx

`<TextArea` was not filling height of parent container. This was increasing vertical padding between form elements any time `<TextArea` was used inside a `<FormBox`.
BEFORE | AFTER
-- | --

fix: Add display block to `<TextArea`

---

src/components/Radio/RadioGroupMinimal.tsx

Match bottom margin of `<RadioGroupMinimal`'s legend to bottom margin of other form components' labels.

style: Reduce bottom margin of `<RadioGroupMinimal` legend

---

src/styles/__snapshots__/createTheme.test.ts.snap
src/styles/createTheme.test.ts
src/styles/createTheme.ts

**Changes**
- Override theme breakpoints - reverted back to previous default values
- [MUI changed the default values ](https://github.com/mui/material-ui/issues/21902)

fix: override breakpoints

---

src/components/TableModule/TableHeaderCell.tsx
src/components/TableModule/TableModule.stories.tsx
src/components/TableModule/TableModule.tsx
src/components/TableModule/TableModuleRow.tsx

- While implementing sticky columns in PHC's OE I found some issues that needed to be fixed
- Sticky header zIndex needed to be higher than the cells below
- Got zIndex order right for the rightmost header cell and the action button cell
- Redid the right border as a box shadow because in some situations the border was scrolling when it should have been sticky
- Updated the Sticky Story to make sure the new zIndicies work both vertically and horizontally
https://user-images.githubusercontent.com/5824697/203387793-37f5db56-2767-4531-a3c8-a38e0b2164ff.mov
https://user-images.githubusercontent.com/5824697/203387824-d75c4ca9-68fe-42f5-95d9-b593ad0284a5.mov

[NO-JIRA] Improve TableModule Sticky Columns

---

src/components/TableModule/TableModule.tsx

PR in `phc-ui` is failing tests in GitHub, but not in my local. There are a few issues, but one is I was throwing an error for all tables without a ref, when only the tables with sticky columns need the ref.
- Changed the error to a warning
- Added checks so all sticky `useEffects` only run for tables with sticky columns

[NO-JIRA] Improve TableModule sticky useEffects and ref warning

---

.github/lifeomic-probot.yml

This probot behavior allows reporting `master` build failures to a Slack channel. For our open source repos, we should use `#open-source`.
https://github.com/lifeomic/probot#reportworkflowfailures

chore: start reporting master build failures to #open-source

---

src/components/TableModule/TableModule.tsx
src/components/TableModule/TableModuleRow.tsx

- Previous changes made it so you had to scroll to the end of a table's columns to access the hoverable context menu on a row
- The desired effect is to see this context menu at all times, even on tables with tons of columns
BEFORE | AFTER
-- | --
- Removal of a class, `sticky`, that made the menu stick to the right of the table
- Since there were both `sticky` and `isSticky` classes, I took `sticky` for being redundant and removed it
- Added class back to TableModule and TableModuleRow
- Renamed it `stickyMenuButton` to eliminate future confusion

[NO-JIRA] Make TableModule Row Menu Sticky Again

---

src/components/TableModule/TableModule.stories.tsx
src/components/TableModule/TableModule.test.tsx
src/components/TableModule/TableModule.tsx
src/components/TableModule/types.ts

It uses the [row selection API](https://tanstack.com/table/v8/docs/api/features/row-selection) from tanstack to simplify developers' learning curve.
This is an temporary solution before fully adopting the TanStack table API via #331

feat(PHC-4380): row selection to TableModule

---

src/components/TableModule/TableModule.stories.tsx
src/components/TableModule/TableModuleRow.test.tsx
src/components/TableModule/TableModuleRow.tsx

This seems a known problem of `TableModule` where click event on checkbox in a cell will also trigger row click.
row selection event will trigger row click
row selection via checkbox will not trigger row click

fix: Disable row handler when clicking on a checkbox

---

.github/workflows/pr-branch-build.yml
.github/workflows/release.yml

Fixes this warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

ci: upgrade deprecated actions

---

src/components/TableModule/TableModule.tsx

This will support backward compatibility where table row will be kept as they were when row selection is disabled (default option).

fix(PHC-4380): achieves backward compatibility #331

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.tsx
src/components/Select/SelectOption.tsx

- Added new properties to `<SelectOption />` to allow for a 'secondaryAction' so that you can both select an option's value in the parent `<Select />` `onChange` and do something else with the individual `<SelectOption />` (e.g. navigate somewhere with more info about the option)
- Update Select story so it actually selects the value when you click an option
- @dexterca, when you get back into the office, can I get your opinion on the design of this? We can add a link as `children` to a <SelectOption /> as it is, but this takes a lot more vertical space and imo is a little harder to tell which option each link goes with at first glance. Thoughts?
| *As-is option* | *Example new option from this PR* |
|---|---|
| ![Screenshot 2023-04-20 at 5 05 43 …

[PHC-4098] Add secondaryAction to SelectOption

---

src/components/TableModule/TableModule.test.tsx
src/components/TableModule/TableModule.tsx

Since `row` is in `any` type, when it has a read-only property like `__typename` when the row data comes from a GQL response object, the `Object.assign()` will fail. E.g.,
```
TypeError: Cannot assign to read only property '__typename' of object '#<Object>'
at Function.assign (<anonymous>)
```

PHC-4300 Fixes TypeError when rowData has read-only property

---

src/components/TableModule/TableHeaderCell.tsx
src/components/TableModule/TableModule.tsx

I wanted to lighten sticky cell background in order to make disabled checkboxes more visible. This also enabled me to use `palette.divider` color for sticky right border color. I also doubled the width of the right-border from `2px` to `4px` to help with delineation between sticky and static.
Another win for using `palette.divider` is we now have a continuous vertical line. Whereas with `primary.main` we had a disconnected blue divider due to the use of two different colors.
BEFORE | AFTER
-- | --

Adjust sticky column border-color, -width and background colors

---

src/components/TableModule/TableModule.stories.tsx
src/components/TableModule/TableModule.tsx
src/components/TableModule/TableModuleRow.tsx

Add an optional prop `rowIndex` to `rowActions` to be able to delete current row from table

fix(TableModule): provide rowIndex to rowActions

---

src/components/TableModule/TableModule.stories.tsx
src/components/TableModule/TableModule.tsx
src/components/TableModule/TableModuleCell.tsx
src/components/TableModule/TableModuleRow.tsx

- Added a 3rd option for cell max width
- Added option to wrap cell content instead of cutting it off with `...`
- wrapped option uses `pre-wrap` css property, which respects newlines and spaces in the text content
- Should I write a test to make sure the entire text content is visible? I'm still not sure what's too brittle in front end testing.

[PHC-4736] Wrap cell content

---

src/components/Stepper/Step.test.tsx
src/components/Stepper/Step.tsx

When a button does not specify type, then the default is "submit" when inside a `form` element. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
This pr will fix undesired behavior where if the `Stepper` is used inside a form, then pressing a `Step` will cause the form to submit 
A consumer can fix this by passing `type="button"` to `Step` but the props are not typed as such and I don't think there is a reason not to specify the type for this component

fix: set type of button on step

---

src/components/ExpansionPanel/ExpansionPanel.stories.tsx
src/components/ExpansionPanel/ExpansionPanel.test.tsx
src/components/ExpansionPanel/ExpansionPanel.tsx

- Add option to truncate long titles with '...' in ExpansionPanel
- Needed for a usage of expansion panel in Patient ML where log payloads, which can be quite long, are both the title and the content of an expansion panel.
- Intent is for the full payload to be shown in the content and a truncated preview to be shown in the title

[PML-226] Handle ExpansionPanel long titles

---

src/components/TableModule/TableModule.tsx

- Finally fixing some console pollution I introduced back when we added sticky columns to `<TableModule />`
- We now only show the 'Table doesn't have a ref...' warning if some sticky columns are set
- This will also prevent unnecessary spacing calculations being run when there are no sticky cols
- We also now only show this warning in Dev
This warning appeared for every table on every page that did not have a ref, regardless of whether it needed sticky cols
Now nothing should appear for non-sticky tables, or in Prod

Fix table ref warn

---

src/components/DescriptionList/DescriptionList.stories.tsx
src/components/DescriptionList/DescriptionList.tsx

Add `gap` prop to `<DescriptionList`

---

src/components/DescriptionList/DescriptionList.tsx

Make `<DescriptionList` gap prop consistent with `<Box` gap prop
---

Allow gap to support spacing units

---

.github/workflows/pr-branch-build.yml
package.json
yarn.lock

Looking forward to other repos moving to Node `18.x`, we're making sure Chrōma can support it as well.
- I wasn't 100% certain what to do with the semantic commit for this one. It's not a breaking change and doesn't change anything for our public API, so I'm thinking it should be a patch. Is there a better tag than `fix:` for patches in this case?

Add Node 18.x support

---

src/components/List/List.stories.tsx
src/components/List/List.tsx
src/components/List/ListGroupHeading.tsx
src/components/List/ListItem.tsx

I noticed `title` prop was getting rendered as a `<div>` as a direct descendent of a `<ul>`, which was failing a11y checks due to invalid markup. I'm adjusting the markup in this PR so that `title` precedes the `<ul>`, identical to the way `title` is handled in `<DescriptionList`.
- Add `titleIcon` prop to `<List`
- Make title and title icon styles consistent between list and description list

feat: Add title icon to list

---

src/components/Alert/Alert.stories.tsx
src/components/Avatar/Avatar.stories.tsx

- Removed titles, since those are now created from the component name unless you need to override them
- I spent a couple cycles trying to simplify the templating for Alert, but because we rely on nested components it got complicated. I've abandoned this for now - there's more work to do that's more important.
_There should be no visual differences for these components_

Update A- Components to Storybook CSF3

---

src/components/Box/Box.stories.tsx
src/components/Breadcrumbs/Breadcrumbs.stories.tsx
src/components/Button/Button.stories.tsx
src/components/ButtonFilePicker/ButtonFilePicker.stories.tsx
src/components/ButtonFloat/ButtonFloat.stories.tsx
src/components/ButtonLink/ButtonLink.stories.tsx
src/components/ButtonUnstyled/ButtonUnstyled.stories.tsx

- Removed titles, since those are now created from the component name unless you need to override them
- except for `Box`, which is organized into the Layout group
-  Added Stories for Outlined and Text variants on `Button` so we have examples of those properties on at least one button component
- Increased height on `ButtonFloat` stories wrapper so it doesn't get cut off by outer window
| --- | --- |
| ![Screenshot 2023-08-22 at 4 22 03 PM](https://github.com/lifeomic/chroma-react/assets/5824697/030e029a-6e97-4f5e-bd38-6bab6f3564 …

Update B- Components to Storybook CSF3

---

.github/workflows/pr-branch-build.yml
.gitignore

it doesn't build storybook during PR and branch build workflow
it will exercise the target `docs:build` during PR and branch build workflow.
Although it adds 30s more to the build time, it will make sure the storybook setup works all the time

build: includes docs:build target into branch build workflow

---

src/components/SlideOver/Actions.tsx
src/components/SlideOver/Header.test.tsx
src/components/SlideOver/Header.tsx
src/components/SlideOver/SlideOver.stories.tsx

- Add `titleIcon` prop to `<Header`
- Move close icon to the right by 10px
- Add padding around actions footer
- Add spacing between actions
- Update tests
BEFORE | AFTER | &nbsp;
-- | -- | --
N/A | <img width="449" alt="Screenshot 2023-08-23 at 1 46 29 PM" src="https://github.com/lifeomic/chroma-react/assets/485903/f10794d4-ba0e-4fd4-84de-a8553f3b2143"> | Add `titleIcon`

feat: Add Slideover title icon

---

src/components/Checkbox/Checkbox.stories.tsx
src/components/Chip/Chip.stories.tsx
src/components/ColorPicker/ColorPicker.stories.tsx
src/components/Select/ComboBox.stories.tsx

- Removed redundant title property from Chip
-  Added Stories for disabled property on `Chip`
-  Fixed a rendering issue that was leaving the indeterminate checkboxes empty
- Increased height on `ColorPicker` stories wrapper so it doesn't get cut off by outer window
- A future improvement we could make would be to change the popup window to float over the content like the `ComboBox`'s does
| --- | --- |
| ![Screenshot 2023-08-22 at 5 27 58 PM](https://github.com/lifeomic/chroma-react/assets/5824697/5d616da1-97e6-4409-a1d4-86ccdc2a …

Update C- Component to Storybook CSF3

---

src/components/Modal/Modal.test.tsx
src/components/Modal/ModalActions.tsx

- Leverage Box's `justify` property to control `justifyActions` vs class styling
- Use Box's `gap` prop to space modal actions vs right margin styling
**NOTE**: No visual changes

Refactor `<ModalActions` spacing and `justifyActions` prop

---

src/components/DayPicker/DayPicker.stories.tsx
src/components/Divider/Divider.stories.tsx
src/components/DotLoader/DotLoader.stories.tsx

-  Added Stories for `DotLoader` small and styled args, as well as `Divider` row arg
- Increased height on `DayPicker` stories wrapper so it doesn't get cut off by outer window - in the future, we could look into making the `DayPicker` calendar popup float above its parent content like `Select` and `ComboBox`
- _`DescriptionList` Components will be the next PR, to try to keep this one to a reasonable size_
| --- | --- |
| ![Screenshot 2023-08-23 …

Update D- Components to Storybook CSF3

---

src/components/LayoutManager/LayoutManager.stories.tsx
src/components/LinearProgress/LinearProgress.stories.tsx
src/components/Link/Link.stories.tsx

- Added a little padding to 'Main Content' in `LayoutManager`
- Added color story to `Link`
| --- | --- |
| ![Screenshot 2023-08-24 at 4 58 31 PM](https://github.com/lifeomic/chroma-react/assets/5824697/458da968-3df6-4c80-bafc-d1740787cdad) | ![Screenshot 2023-08-24 at 4 48 57 PM](https://github.com/lifeomic/chroma-react/assets/5824697/e8adbd5e-b1ae-46ba-ac59-e1ea9f57281a) |

Update L- Components to Storybook CSF3

---

src/components/ExpansionPanel/ExpansionPanel.stories.tsx
src/components/FormBox/FormBox.stories.tsx
src/components/Header/Header.stories.tsx

- Added title to left in Default `Header` so it doesn't look empty
| --- | --- |
| ![Screenshot 2023-08-23 at 5 20 03 PM](https://github.com/lifeomic/chroma-react/assets/5824697/181029ee-08ed-44b7-99fe-56d60c397a7d) | ![Screenshot 2023-08-23 at 5 17 46 PM](https://github.com/lifeomic/chroma-react/assets/5824697/c6bbb6e7-eb73-4d28-a333-1482791160fa) |

Update E- to H- Components to Storybook CSF3

---

src/components/IconTile/IconTile.stories.tsx
src/components/InfiniteScroll/InfiniteScroll.stories.tsx
src/components/KeymapHelp/KeymapHelp.stories.tsx

- KeymapHelp cites a GitHub Issue from 2019 that is not officially closed. I see there were some posts in 2020-21 that have a workaround which received a complaint of performance issues.
- If someone thinks we need to try this workaround I can apply it in another PR. Skipping for now in order to get through updating all the components in a timely manner. 
_Nothing should have changed visually_

Update I- to K- Components to Storybook CSF3

---

src/components/SlideOver/Header.tsx

This PR adjusts the layout for children of `<Header` in `<SlideOver` and also adds text overflow ellipsis for the panel title.
- Adjust layout for `<Header` children
- Add min-height and -width so `titleIcon` does not shrink
BEFORE | AFTER
-- | --

fix: Adjust layout of `<SlideOver` children and add text overflow for panel title

---

src/components/Menu/Menu.stories.tsx
src/components/Menu/MenuItem.stories.tsx
src/components/Modal/Modal.stories.tsx

- `Menu`
- Added Title, Gutter, and usePortal stories
- Increased height to show whole menu in non-portal stories
- `MenuItem`
- Unlike in `List` (#383) and `DescriptionList` (#377), I decided to keep `MenuItem` stories separate, because `Menu` had enough of its own stories that didn't rely on the different stylings of `MenuItem` that putting them all together felt a little cluttered and confusing.
- Refined the custom header styling in `Modal`
| …

Update M- Components to Storybook CSF3

---

src/components/NumberFormat/PercentFormatField.stories.tsx
src/components/NumberFormat/PhoneNumberFormatField.stories.tsx
src/components/NumberFormat/PriceFormatField.stories.tsx
src/components/NumberFormat/UnitNumberFormatField.stories.tsx

- `PhoneNumberFormatField`
- Added `showRequiredLabel: true` to all components' error story, since it made semantic sense with the error story we were telling
- All components except `PhoneNumberFormatField`
- Because `PhoneNumberFormatField` does not have many props the other three do, it did not receive these stories
- Added
- Required story, same as `PhoneNumberFormatField`
- Adornments
- Tooltip Message / Icon
- You might notice I didn't add a story for every single prop. My heuristic is if the property involves a React Node/Icon or is …

Update NumberFormat Components to Storybook CSF3

---

src/components/PageLayout/PageLayout.stories.tsx
src/components/Paper/Paper.stories.tsx
src/components/Pill/Pill.stories.tsx

- Added a couple `Pill` styling stories
- Added content to `Paper` default story
| --- | --- |
| ![Screenshot 2023-08-29 at 3 43 05 PM](https://github.com/lifeomic/chroma-react/assets/5824697/69dfaac6-2c67-42c2-bda4-bdc94bb6e2f5) | ![Screenshot 2023-08-29 at 3 42 41 PM](https://github.com/lifeomic/chroma-react/assets/5824697/fb5913dd-8c15-420f-a1fe-f6d278df30d1) |

Update first half of P- Components to Storybook CSF3

---

src/components/Popover/Popover.stories.tsx
src/components/PrimaryNavigation/PrimaryNavigation.stories.tsx

- Added several `Popover` styling stories
- Increased height of `Popover` Stories
- made the tallest menu Popover a portal so it didn't have to be quite so tall
- Added some padding to the content
| --- | --- |
| ![Screenshot 2023-08-29 at 4 26 13 PM](https://github.com/lifeomic/chroma-react/assets/5824697/624c986c-8a35-495b-8a54-332d8a2b2474) | ![Screenshot 2023-08-29 at 4 23 40 PM](https://github.com/lifeomic/chroma-react/assets/5824697/6a4bebd1- …

Update second half of P- Components to Storybook CSF3

---

src/components/Radio/Radio.stories.tsx
src/components/Radio/RadioGroup.stories.tsx
src/components/Radio/RadioGroupMinimal.stories.tsx

- Added color inverse stories to all components
- Added Icon story to `Radio`
- Noticed `Radio` has `hasError` and `errorMessage` props from extending `BaseFormElement`, but does not implement them. We'll need to take care of this (or omit the props if people aren't using them anywhere) in a future PR

Update R- Components to Storybook CSF3

---

src/components/SearchField/SearchField.stories.tsx
src/components/SecondaryNavigation/SecondaryNavigation.stories.tsx
src/components/SecondaryNavigation/SecondaryNavigationItem.stories.tsx

- Removed With Label Story from `SearchField`
`SearchField` does not currently implement a label. We could change this in a future PR, but removing this story for now.
_Nothing should have visually changed with the other two components_

Update first batch of S- Components to Storybook CSF3

---

src/components/Select/Select.stories.tsx
src/components/Skeleton/Skeleton.stories.tsx
src/components/SlideOver/SlideOver.stories.tsx

- `Select`
- _nothing should have changed visually_
- There could be some properties that could use new or modified stories, but I want to get the first round done before diving into this
- `Skeleton`
- I modified the `Skeleton`'s size so it looks more like it might when loading a block of text on a page
- `SlideOver`
- The page was unable to scroll with open `SlideOver`s in the stories
- This is now fixed by starting with all `SlideOver`s closed and having a button …

Update second batch of S- Components to Storybook CSF3

---

src/components/Slider/Slider.stories.tsx
src/components/SmallTile/SmallTile.stories.tsx
src/components/Snackbar/Snackbar.stories.tsx

- `Snackbar`
- Added a story to cover Icon as well as the warning styling
- Increased Story height so we can see whole component
- Snackbar doesn't appear to implement its title prop
- _Nothing should have changed visually with the other two components_
- `Slider` could potentially use more stories. I think this and former components in a similar position merit a discussion about which stories to make and which to rely on the live prop manipulation feature for
| …

Update third batch of S- Components to Storybook CSF3

---

src/components/SpinButton/SpinButton.stories.tsx
src/components/Stepper/Stepper.stories.tsx

- `Stepper`
- Added number controls so you can test out setting all the new props @dexterca just added
- Decided not to make stories because you can check these out by modifying the props - considering going back and doing this for our other components, and will likely call a quick Chroma meeting for this
_Side note: I have no idea why marginBottom is rendering apart from all the other margin props. It's written right under MarginTop in all places in Stepper.tsx_

Update fourth round of S- Components to Storybook CSF3

---

src/components/Tabs/Tabs.stories.tsx
src/components/Text/Text.stories.tsx
src/components/TextArea/TextArea.stories.tsx

- `Tabs`
- Added a story for `manualControl`, which was unable to be demonstrated by adjusting the props
- It's a halfway solution that could be improved
- the `onClick()` functions are obfuscated in Storybook, so a completely new Chrōma user without reference to usage of Tabs in phc-ui, for example, may not quite be able to figure out how to set this up.
- the proper way to do `manualControl` within a story involves the Storybook `Actions` and/or `State` add-ons.
- …

Update first half of T- Components to Storybook CSF3

---

src/components/TextField/TextField.stories.tsx
src/components/Toggle/Toggle.stories.tsx
src/components/Tooltip/Tooltip.stories.tsx

- `Tooltip`
- Added a couple stories demonstrating different children, since that prop is hard to set in the interactive area with our current setup

Update second half of T- Components to Storybook CSF3

---

stories/styles/theme/theme.stories.tsx

- condensed some style tags to a class
- Changed Theme Explorer theme to light to match the rest of the content around it
- Nothing in the example made use of the Secondary Palette, so I removed it for now.
- If there's time in the future, I'd love to study up on our theming and make an example that actually illustrates how our secondary palette works. But for now it's more important to jump on some Patient ML and client work.
| --- | --- |
| ![Screenshot 2023-09-05 at 2 41 30 PM](https://github.com/lifeomic/chroma-react/assets/5824697/4b151e2b-2f9c-4352-8dd5-13b3423ed01a) | ![Screenshot 2023-09-05 at 2 …

Update theme to Storybook CSF3

---

src/components/DescriptionList/DescriptionList.tsx

- This has come up twice now in `phc-ui` - we want to conditionally add an element to the `<DescriptionList />` `items` array - [conditional description example](https://github.com/lifeomic/phc-ui/pull/3457#discussion_r1333771209) and [conditional divider example](https://github.com/lifeomic/phc-ui/blob/1d9468ae761a10be8e5d54c8cae51f085765fa5f/src/components/pages/ML/components/DescriptionList.tsx#L38)
- So rather than deal with it individually, I think it makes sense to take care of this at the source

Allow null in description list items

---

src/components/ExpansionPanel/ExpansionPanel.tsx

BEFORE | AFTER | &nbsp;
-- | -- | --

Adjust `<ExpansionPanel` icons' min-widths to fix Safari display bug

---

src/components/List/ListItem.tsx

Adds support for adding custom classnames to icon and trailing icon in  `<ListItem`

feat: Add custom classname for icon and trailing icon in `<ListItem`

---

src/components/ExpansionPanel/ExpansionPanel.stories.tsx
src/components/ExpansionPanel/ExpansionPanel.tsx

We have a use case where we want to add secondary actions (or content) to the expansion panel header. This required some refactoring of the button element, which included adding an `<IconButton` so that we could allot some space for content to go between the clickable title and plus icon.

feat: Add secondary header to `<ExpansionPanel`

---

package.json
src/components/Alert/AlertIcon.tsx
src/components/Button/Button.tsx
src/components/ButtonFloat/ButtonFloat.tsx
src/components/ButtonLink/ButtonLink.tsx
src/components/ColorPicker/ColorPicker.tsx
src/components/DescriptionList/DescriptionDetails.tsx
src/components/DescriptionList/DescriptionList.tsx
src/components/DescriptionList/DescriptionTerm.tsx
src/components/ExpansionPanel/ExpansionPanel.tsx
src/components/IconButton/IconButton.tsx
src/components/IconButtonFloat/IconButtonFloat.tsx
src/components/IconTile/IconTileBadge.tsx
src/components/List/List.tsx
src/components/List/ListItem.tsx
src/components/Menu/MenuButton.tsx
src/components/Menu/MenuItem.tsx
src/components/Popover/PopoverItem.tsx
src/components/Radio/Radio.tsx
src/components/Select/ComboBox.tsx
src/components/Select/Select.tsx
src/components/Select/SelectOption.tsx
src/components/SlideOver/Header.tsx
src/components/Snackbar/Snackbar.tsx
src/components/Stepper/Step.tsx
src/components/TextArea/TextArea.tsx
src/components/TextField/TextField.tsx
src/testUtils/IconComponent.tsx
yarn.lock

The icon typings here need to be updated so the latest version of `chromicons` can be used in PHC-UI.

feat: Update chromicons and icon typings

---

src/components/Select/Select.tsx

The current Selector sets the popover's width to the button's width. This PR adds a optional `popoverStyle` to control the popover's width. The end-goal is to build the component below.

feat: add optional popoverStyle param to Select
